CC=cc
CFLAGS=-Wall -Wextra -Werror

run00:
	$(CC) $(CFLAGS) ./main_00.c ./ex00/*.c && ./a.out  && rm *.out

run01:
	$(CC) $(CFLAGS) ./main_01.c ./ex01/*.c && ./a.out  && rm *.out

run02:
	$(CC) $(CFLAGS) ./main_02.c ./ex02/*.c && ./a.out  && rm *.out

run03:
	$(CC) $(CFLAGS) ./main_03.c ./ex03/*.c && ./a.out  && rm *.out

run04:
	$(CC) $(CFLAGS) ./main_04.c ./ex04/*.c && ./a.out  && rm *.out

run05:
	$(CC) $(CFLAGS) ./main_05.c ./ex05/*.c && ./a.out  && rm *.out

run06:
	$(CC) $(CFLAGS) ./main_06.c ./ex06/*.c && ./a.out  && rm *.out

run07:
	$(CC) $(CFLAGS) ./main_07.c ./ex07/*.c && ./a.out  && rm *.out

run08:
	$(CC) $(CFLAGS) ./main_08.c ./ex08/*.c && ./a.out  && rm *.out
