# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: myokogaw <myokogaw@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/05/01 15:58:05 by myokogaw          #+#    #+#              #
#    Updated: 2023/05/01 18:56:47 by myokogaw         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

# Name of Project
NAME = libft.a

# Compiler
CC = gcc

# Compiler Flags
CFLAGS := -c -Wall -Werror -Wextra

# Functions
FTS := srcs/ft_print_params.c srcs/ft_sort_params.c

all: $(NAME)
	${CC} ${CFLAGS} {FTS}